echo "" > $HOME/.config/alacritty/alacritty.yml
cat $HOME/.config/alacritty/configfiles/env.yml >> $HOME/.config/alacritty/alacritty.yml
cat $HOME/.config/alacritty/configfiles/shell-osx.yml >> $HOME/.config/alacritty/alacritty.yml
cat $HOME/.config/alacritty/configfiles/window.yml >> $HOME/.config/alacritty/alacritty.yml
cat $HOME/.config/alacritty/configfiles/windows-osx.yml >> $HOME/.config/alacritty/alacritty.yml
cat $HOME/.config/alacritty/configfiles/scroll.yml >> $HOME/.config/alacritty/alacritty.yml
cat $HOME/.config/alacritty/configfiles/nord.yml >> $HOME/.config/alacritty/alacritty.yml
cat $HOME/.config/alacritty/configfiles/opacity.yml >> $HOME/.config/alacritty/alacritty.yml
cat $HOME/.config/alacritty/configfiles/cursor.yml >> $HOME/.config/alacritty/alacritty.yml
cat $HOME/.config/alacritty/configfiles/font.yml >> $HOME/.config/alacritty/alacritty.yml
cat $HOME/.config/alacritty/configfiles/font-osx.yml >> $HOME/.config/alacritty/alacritty.yml
cat $HOME/.config/alacritty/configfiles/mouse-osx.yml >> $HOME/.config/alacritty/alacritty.yml
cat $HOME/.config/alacritty/configfiles/mouse-bindings.yml >> $HOME/.config/alacritty/alacritty.yml
cat $HOME/.config/alacritty/configfiles/keys-osx.yml >> $HOME/.config/alacritty/alacritty.yml
cat $HOME/.config/alacritty/configfiles/vi-mode.yml >> $HOME/.config/alacritty/alacritty.yml