echo "" > $HOME/AppData/Roaming/alacritty/alacritty.yml
cat $HOME/AppData/Roaming/alacritty/configfiles/env.yml >> $HOME/AppData/Roaming/alacritty/alacritty.yml
cat $HOME/AppData/Roaming/alacritty/configfiles/shell-pc.yml >> $HOME/AppData/Roaming/alacritty/alacritty.yml
cat $HOME/AppData/Roaming/alacritty/configfiles/window.yml >> $HOME/AppData/Roaming/alacritty/alacritty.yml
cat $HOME/AppData/Roaming/alacritty/configfiles/windows-pc.yml >> $HOME/AppData/Roaming/alacritty/alacritty.yml
cat $HOME/AppData/Roaming/alacritty/configfiles/scroll.yml >> $HOME/AppData/Roaming/alacritty/alacritty.yml
cat $HOME/AppData/Roaming/alacritty/configfiles/nord.yml >> $HOME/AppData/Roaming/alacritty/alacritty.yml
cat $HOME/AppData/Roaming/alacritty/configfiles/opacity.yml >> $HOME/AppData/Roaming/alacritty/alacritty.yml
cat $HOME/AppData/Roaming/alacritty/configfiles/cursor.yml >> $HOME/AppData/Roaming/alacritty/alacritty.yml
cat $HOME/AppData/Roaming/alacritty/configfiles/font.yml >> $HOME/AppData/Roaming/alacritty/alacritty.yml
cat $HOME/AppData/Roaming/alacritty/configfiles/mouse-pc.yml >> $HOME/AppData/Roaming/alacritty/alacritty.yml
cat $HOME/AppData/Roaming/alacritty/configfiles/mouse-bindings.yml >> $HOME/AppData/Roaming/alacritty/alacritty.yml
cat $HOME/AppData/Roaming/alacritty/configfiles/keys-pc.yml >> $HOME/AppData/Roaming/alacritty/alacritty.yml
cat $HOME/AppData/Roaming/alacritty/configfiles/vi-mode.yml >> $HOME/AppData/Roaming/alacritty/alacritty.yml